export const ADD_STOCK: string = 'ADD_STOCK';
export type ADD_STOCK = typeof ADD_STOCK;

export const ADD_STOCK_CHANGE: string = 'ADD_STOCK_CHANGE';
export type ADD_STOCK_CHANGE = typeof ADD_STOCK_CHANGE;

export const ADD_HOLDING: string = 'ADD_HOLDING';
export type ADD_HOLDING = typeof ADD_HOLDING;

export const FETCH_STOCK_QUOTE_START: string = 'FETCH_STOCK_QUOTE_START';
export type FETCH_STOCK_QUOTE_START = typeof FETCH_STOCK_QUOTE_START;

export const FETCH_STOCK_QUOTE_SUCCESS: string = 'FETCH_STOCK_QUOTE_SUCCESS';
export type FETCH_STOCK_QUOTE_SUCCESS = typeof FETCH_STOCK_QUOTE_SUCCESS;

export const FETCH_STOCK_QUOTE_ERROR: string = 'FETCH_STOCK_QUOTE_ERROR';
export type FETCH_STOCK_QUOTE_ERROR = typeof FETCH_STOCK_QUOTE_ERROR;

export const UPDATE_SHARE_COUNT: string = 'UPDATE_SHARE_COUNT';
export type UPDATE_SHARE_COUNT = typeof UPDATE_SHARE_COUNT;